---
- name: config | Create configuration file
  ansible.builtin.template:
    src: torrserver.config.j2
    dest: "{{ torrserver_install_dir }}/{{ torrserver_service_name }}.config"
    owner: "{{ torrserver_user }}"
    group: "{{ torrserver_group }}"
    mode: "0644"
  notify: Restart torrserver

- name: config | Show configuration file
  ansible.builtin.slurp:
    src: "{{ torrserver_install_dir }}/{{ torrserver_service_name }}.config"
  register: config_file_content

- name: config | Display configuration file contents
  ansible.builtin.debug:
    msg: "{{ config_file_content.content | b64decode }}"

- name: config | Create authentication file
  ansible.builtin.template:
    src: accs.db.j2
    dest: "{{ torrserver_install_dir }}/accs.db"
    owner: "{{ torrserver_user }}"
    group: "{{ torrserver_group }}"
    mode: "0600"
  when: torrserver_enable_auth
  notify: Restart torrserver
