---
- name: config | Resolve TorrServer version capabilities
  ansible.builtin.include_tasks:
    file: version.yml
    apply:
      tags:
        - torrserver
        - config
        - version
  tags:
    - torrserver
    - config
    - version

- name: config | Create configuration file
  ansible.builtin.template:
    src: torrserver.config.j2
    dest: "{{ torrserver_install_dir }}/{{ torrserver_service_name }}.config"
    owner: "{{ torrserver_user }}"
    group: "{{ torrserver_group }}"
    mode: "0644"
  notify: Restart torrserver
  tags:
    - daemon_config

- name: config | Show configuration file
  ansible.builtin.slurp:
    src: "{{ torrserver_install_dir }}/{{ torrserver_service_name }}.config"
  register: config_file_content
  tags:
    - debug

- name: config | Display configuration file contents
  ansible.builtin.debug:
    msg: "{{ config_file_content.content | b64decode }}"
  tags:
    - debug

- name: config | Create authentication file
  ansible.builtin.template:
    src: accs.db.j2
    dest: "{{ torrserver_install_dir }}/accs.db"
    owner: "{{ torrserver_user }}"
    group: "{{ torrserver_group }}"
    mode: "0600"
  when: torrserver_enable_auth
  notify: Restart torrserver
  tags:
    - auth

- name: config | Create settings.json file
  ansible.builtin.template:
    src: settings.json.j2
    dest: "{{ torrserver_install_dir }}/settings.json"
    owner: "{{ torrserver_user }}"
    group: "{{ torrserver_group }}"
    mode: "0644"
  notify: Restart torrserver
  tags:
    - settings
