---
- name: install | Set installation method fact
  ansible.builtin.set_fact:
    torrserver_use_local: "{{ torrserver_local_file is defined and torrserver_local_file != '' and torrserver_local_file is not none }}"
  tags:
    - facts

- name: install | Check installed version
  ansible.builtin.command: "{{ torrserver_install_dir }}/{{ torrserver_bin_prefix }}-{{ architecture }} --version"
  register: installed_version_cmd
  ignore_errors: true
  changed_when: false
  tags:
    - facts

- name: install | Set installed version fact
  ansible.builtin.set_fact:
    torrserver_installed_tag: "{{ installed_version_cmd.stdout | regex_search('MatriX\\.\\d+') }}"
  when: installed_version_cmd.rc == 0
  tags:
    - facts

- name: install | Install from local file
  ansible.builtin.include_tasks:
    file: install_local.yml
    apply:
      tags:
        - torrserver
        - install
        - install_local
  tags: always
  when: torrserver_use_local | bool

- name: install | Install from remote repository
  ansible.builtin.include_tasks:
    file: install_remote.yml
    apply:
      tags:
        - torrserver
        - install
        - install_remote
  tags: always
  when: not (torrserver_use_local | bool)
