---
- name: Setup environment
  ansible.builtin.include_tasks:
    file: setup.yml
    apply:
      tags:
        - torrserver
        - setup
  tags:
    - torrserver
    - setup
    - dependencies
    - user

- name: Install TorrServer
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - torrserver
        - install
  tags:
    - torrserver
    - install
    - facts
    - install_local
    - install_remote

- name: Configure TorrServer
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - torrserver
        - config
  tags:
    - torrserver
    - config
    - version
    - daemon_config
    - auth
    - settings
    - debug

- name: Configure BBR
  ansible.builtin.include_tasks:
    file: bbr.yml
    apply:
      tags:
        - torrserver
        - bbr
  tags:
    - torrserver
    - bbr

- name: Manage TorrServer service
  ansible.builtin.include_tasks:
    file: service.yml
    apply:
      tags:
        - torrserver
        - service
  tags:
    - torrserver
    - service
    - systemd
