---
- name: service | Create systemd service file
  ansible.builtin.template:
    src: torrserver.service.j2
    dest: /etc/systemd/system/{{ torrserver_service_name }}.service
    mode: "0644"
  notify: Restart torrserver

- name: service | Enable and start torrserver service
  ansible.builtin.systemd:
    name: "{{ torrserver_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
  register: service_result

- name: service | Check torrserver service status
  when: service_result.changed
  block:
    - name: Check torrserver service status
      ansible.builtin.service_facts:

    - name: Assert torrserver service is active
      ansible.builtin.assert:
        that:
          - ansible_facts.services[torrserver_service_name + '.service'] is defined
          - ansible_facts.services[torrserver_service_name + '.service'].state == "running"
        fail_msg: "torrserver service is not running"
        success_msg: "torrserver service is running"
  rescue:
    - name: Fail if torrserver service is not running
      ansible.builtin.fail:
        msg: "torrserver service is not running (status: {{ ansible_facts.services[torrserver_service_name + '.service'].state }})"
