---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    torrserver_service_name: torrserver
  tasks:
    - name: Check torrserver service status
      ansible.builtin.service_facts:

    - name: Assert torrserver service is active
      ansible.builtin.assert:
        that:
          - ansible_facts.services[torrserver_service_name + '.service'] is defined
          - ansible_facts.services[torrserver_service_name + '.service'].state == "running"
        fail_msg: "torrserver service is not running"
        success_msg: "torrserver service is running"
